version: "3.8"

networks:
  sharedNetwork:

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - sharedNetwork
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        interval: 30s
        timeout: 10s
        retries: 5

  app:
    image: rabbitmq-dotnet-app
    build: .
    ports:
      - "5064:80"
    networks:
      - sharedNetwork
    depends_on:
      rabbitmq:
        condition: service_healthy